# Generated by Django 2.1.5 on 2019-07-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_auto_20190726_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=3, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('products', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
