# Generated by Django 2.1.5 on 2019-08-24 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0003_orderdetail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='total',
        ),
    ]
