version: '3'

services:
  db-store-petgula:
    image: postgres
    ports:
      - "6432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
  store_backend :
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/store_backend
    ports:
      - "8000:8000"
    depends_on:
      - db-store-petgula