# Generated by Django 2.1.5 on 2019-07-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='allowed',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CREDITO', 'credito'), ('DEBITO', 'Debito')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
