# Generated by Django 2.1.5 on 2019-06-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('payday', models.DateField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=7)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
