# Generated by Django 2.1.5 on 2019-05-20 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='products',
            new_name='products_storage',
        ),
    ]
