# Generated by Django 2.0.4 on 2019-04-19 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='products',
        ),
        migrations.AddField(
            model_name='sell',
            name='products_storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='storage.Storage'),
            preserve_default=False,
        ),
    ]
