# Generated by Django 2.1.5 on 2019-05-18 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_amount'),
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='products_storage',
        ),
        migrations.AddField(
            model_name='sell',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
            preserve_default=False,
        ),
    ]
