# Generated by Django 2.1.5 on 2019-05-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0002_auto_20190518_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='unit',
            field=models.CharField(choices=[('Kg', 'kg'), ('g', 'g'), ('UND', 'und'), ('SC', 'sc')], default='UND', max_length=3),
        ),
    ]
