# Generated by Django 2.1.5 on 2019-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0003_auto_20190518_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='sell',
            name='unit',
            field=models.CharField(choices=[('Kg', 'kg'), ('UND', 'und'), ('SC', 'sc')], default='UND', max_length=3),
        ),
    ]
