# Generated by Django 2.1.5 on 2019-07-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('ship_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
