# Generated by Django 2.1.5 on 2019-07-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('order_details', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_details.OrderDetail'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Payment'),
        ),
    ]
