# Generated by Django 2.1.5 on 2019-09-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_date',
            field=models.DateField(auto_now=True),
        ),
    ]
