# Generated by Django 2.1.5 on 2019-09-05 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190905_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
    ]
