# Generated by Django 2.0.4 on 2019-09-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_active'),
        ('order', '0005_auto_20190824_2004'),
    ]

    operations = [
    ]
