# Generated by Django 2.1.5 on 2019-05-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'kg'), ('UND', 'und'), ('SC', 'sc')], default='UND', max_length=3),
        ),
    ]
