# Generated by Django 2.0.4 on 2019-04-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190407_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
