# Generated by Django 2.1.5 on 2019-05-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'kg'), ('G', 'g'), ('UND', 'und'), ('SC', 'sc')], default='UND', max_length=3),
        ),
    ]
