# Generated by Django 2.1.5 on 2019-04-13 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190407_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='unit',
            field=models.CharField(choices=[('KG', 'kg'), ('UND', 'und'), ('SC', 'sc')], default='UND', max_length=3),
        ),
        migrations.AddField(
            model_name='sell',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
