# Generated by Django 2.1.5 on 2019-05-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190518_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'kg'), ('g', 'g'), ('UND', 'und'), ('SC', 'sc')], default='UND', max_length=3),
        ),
    ]
