# Generated by Django 2.0.4 on 2019-09-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unity',
            field=models.CharField(choices=[('KG', 'Kg'), ('SC', 'SC'), ('UND', 'UND')], default='KG', max_length=5),
        ),
    ]
