# Generated by Django 2.1.5 on 2019-04-13 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sell_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell',
            old_name='valor',
            new_name='price',
        ),
    ]
