# Generated by Django 2.1.5 on 2019-04-17 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190413_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sell_itens',
        ),
        migrations.AddField(
            model_name='cart',
            name='sell_itens',
            field=models.ManyToManyField(related_name='sell_itens', to='products.Sell'),
        ),
    ]
