# Generated by Django 2.0.4 on 2019-04-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190417_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='client',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sell_itens',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='client',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='products',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
